service: mern-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    MONGO_URI: monnsdiucsiuecf
    JWT_SECRET: icedjdoisedc

functions:
  app:
    handler: server.handler
    events:
      - httpApi: '*'
